
use `db_test`
drop table if exists `work_data`;
CREATE TABLE `work_data` (
  `id` int(11) DEFAULT NULL,
  `full_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_thai_520_w2 DEFAULT NULL,
  `job_title` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_thai_520_w2 DEFAULT NULL,
  `company` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_thai_520_w2 DEFAULT NULL,
  `country` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_thai_520_w2 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_thai_520_w2;

INSERT INTO `work_data` (`id`, `full_name`, `job_title`, `company`, `country`) VALUES
(1, 'Petrina Grainge', 'Administrative Assistant I', 'Innotype', 'China'),
(2, 'Felix Hambrick', 'VP Product Management', 'Thoughtstorm', 'Portugal'),
(3, 'Doti Triplett', 'Sales Associate', 'Dazzlesphere', 'Argentina'),
(4, 'Herby Branca', 'Database Administrator II', 'Jayo', 'Philippines'),
(5, 'Gunar Terrey', 'Accountant III', 'Voonte', 'Thailand'),
(6, 'Roderick Bransby', 'Senior Quality Engineer', 'Devpulse', 'Philippines'),
(7, 'Chere Cords', 'Human Resources Manager', 'Edgepulse', 'France'),
(8, 'Meta Bilbrey', 'Desktop Support Technician', 'Brainsphere', 'Czech Republic'),
(9, 'Odo Kneller', 'Software Test Engineer IV', 'Youopia', 'Iceland'),
(10, 'Johnnie Konerding', 'Quality Engineer', 'Izio', 'Iran'),
(11, 'Nealy Rodie', 'Food Chemist', 'Ainyx', 'France'),
(12, 'Lisette Danne', 'Senior Developer', 'Minyx', 'Colombia'),
(13, 'Olivie Maryska', 'Clinical Specialist', 'Latz', 'China'),
(14, 'Beatrice Touhig', 'Financial Analyst', 'Bubblemix', 'Russia'),
(15, 'Alessandra Olivier', 'Professor', 'Photolist', 'Indonesia'),
(16, 'Adamo Jeffress', 'Quality Engineer', 'Zoovu', 'China'),
(17, 'Viviene Beccera', 'Engineer I', 'Feedfish', 'China'),
(18, 'Turner Chisholme', 'Staff Scientist', 'Jabbersphere', 'Portugal'),
(19, 'Geordie Merck', 'Technical Writer', 'Tazzy', 'United Kingdom'),
(20, 'Hedvige Sharnock', 'Editor', 'Tagtune', 'Peru'),
(21, 'Prudence Carbry', 'Desktop Support Technician', 'Vimbo', 'Portugal'),
(22, 'Beverly Ivshin', 'Marketing Manager', 'Latz', 'Philippines'),
(23, 'Forster Cecere', 'Physical Therapy Assistant', 'Blognation', 'Mali'),
(24, 'Ermin McKinnell', 'Nuclear Power Engineer', 'Oyoba', 'Yemen'),
(25, 'Marilee Castanyer', 'Legal Assistant', 'Gabvine', 'China'),
(26, 'Scarlet Jeannon', 'Compensation Analyst', 'Feedfish', 'Kazakhstan'),
(27, 'Kamillah Stern', 'Senior Developer', 'Myworks', 'Bolivia'),
(28, 'Haley Sigmund', 'Marketing Manager', 'Twiyo', 'Czech Republic'),
(29, 'Dunstan Meeson', 'Help Desk Operator', 'Leenti', 'South Africa'),
(30, 'Dorine McRuvie', 'Pharmacist', 'Browsecat', 'Russia'),
(31, 'Sephira Duligall', 'GIS Technical Architect', 'Tagtune', 'South Korea'),
(32, 'Godfrey Borwick', 'Financial Analyst', 'Bubblemix', 'Russia'),
(33, 'Bernie Eilert', 'Analyst Programmer', 'Fivebridge', 'Indonesia'),
(34, 'Adlai Vamplus', 'Environmental Tech', 'Podcat', 'Spain'),
(35, 'Selby McCahey', 'Quality Control Specialist', 'Quamba', 'United States'),
(36, 'Reagan Lamas', 'Pharmacist', 'Brightdog', 'Israel'),
(37, 'Darcey Wernham', 'Compensation Analyst', 'Quire', 'Indonesia'),
(38, 'Sapphira Najara', 'Research Associate', 'Demimbu', 'South Korea'),
(39, 'Emelda Marwick', 'Software Consultant', 'Browsebug', 'Indonesia'),
(40, 'Albertine Darington', 'Registered Nurse', 'Camido', 'Indonesia'),
(41, 'Maisey Menat', 'Systems Administrator I', 'Tanoodle', 'Mozambique'),
(42, 'Antonietta Gothrup', 'Sales Associate', 'Jaxbean', 'Indonesia'),
(43, 'Shoshana Frankham', 'Developer II', 'Fivespan', 'China'),
(44, 'Tymon Brettle', 'Recruiting Manager', 'Meemm', 'China'),
(45, 'Dru Cavalier', 'Safety Technician III', 'Kazu', 'Poland'),
(46, 'Chrisy Folkerd', 'Senior Editor', 'Quaxo', 'Israel'),
(47, 'Almeda MacMeeking', 'Research Associate', 'Browsezoom', 'Germany'),
(48, 'Calley Montilla', 'Safety Technician II', 'Meetz', 'China'),
(49, 'Ddene Jagger', 'Legal Assistant', 'Zava', 'United Kingdom'),
(50, 'Barb Iskowitz', 'Account Coordinator', 'Skalith', 'Portugal');